import { defineCommand } from "citty";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { spawn } from "node:child_process";

import wrappedSampleMd from "../../docs/examples/wrapped-2025-sample.md" with { type: "text" };
// Bun types `.html` imports as `HTMLBundle` even with `type: "text"`. At runtime
// the import attribute wins and we get the file contents as a string; the cast
// just tells TypeScript what Bun is doing.
import wrappedSampleHtmlRaw from "../../docs/examples/wrapped-2025-sample.html" with { type: "text" };
const wrappedSampleHtml = wrappedSampleHtmlRaw as unknown as string;

const PULSE_KEPLER = `---
type: pulse
project: kepler
date: 2025-09-19
status: shipped
tracks: [kepler-launch-prep, kepler-auth-migration]
---

# Kepler — 2025-09-19

The launch came together quietly. The auth migration that had been hanging since July landed in two commits, both small, both unglamorous. By the afternoon there was nothing left to do but stage the announcement, which is the kind of evening Janus is happy to record without commentary.

A quieter thread: the migration deprecated the old session token shape, which means tomorrow's pulse will probably mark a track as closed without needing to name what closed it. That's normal. The work was done over weeks; today was just where the calendar landed.

> [!info] Previous pulse: [[2025-09-18--kepler]]
`;

const PULSE_HELIOS = `---
type: pulse
project: helios
date: 2025-09-19
status: in-flight
tracks: [helios-billing-rebuild, helios-vendor-cutover]
---

# Helios — 2025-09-19

Vendor cutover is at the awkward phase: the new provider works for new accounts but the legacy reconciliation job still runs nightly and quietly imports rows from the old system. Two of those rows broke today — wrong currency code, then a duplicate key — and the rest of the afternoon went into the cleanup script rather than the migration itself.

There is a small question whether to finish the cutover this week or wait for the quarterly window. The pulse records the question without answering it.

> [!info] Previous pulse: [[2025-09-18--helios]]
`;

const DAILY_ROLLUP = `---
type: daily-rollup
date: 2025-09-19
projects: [kepler, helios, atlas]
---

# Daily — 2025-09-19

Kepler shipped what had been described in last week's pulse as "the migration we've been not finishing for two months", and the launch followed in the same afternoon. Helios continued the vendor cutover, hit the predictable shape of legacy-data edge cases, and chose not to decide the timing question yet. Atlas did not produce activity today — it remains in the paused state it has held since July.

The week is shaping up around Kepler's launch arc; the weekly rollup on Sunday will likely treat today as the apex.

## Projects

- [[Projects/kepler/pulse/2025-09-19--kepler|Kepler]] — launch landed
- [[Projects/helios/pulse/2025-09-19--helios|Helios]] — vendor cutover, partial
- Atlas — no activity (paused)
`;

const README_DEMO = `# Janus demo vault

This is a *synthetic* vault generated by \`janus demo\`. Nothing here reflects a
real user — the projects (\`kepler\`, \`helios\`, \`atlas\`) are made-up, the dates
are fixed (2025-09-19), the prose is hand-written to illustrate Janus's voice,
and the Wrapped is the deterministic-renderer sample shipped in the repo.

A real Janus install:

- writes to your Obsidian vault (\`obsidianVault\` in \`config.local.json\`),
- uses \`claude -p\` (Claude Code, headless) to synthesize prose from your actual
  git history and Claude Code session transcripts,
- runs every night via \`launchd\` or \`systemd-user\`,
- exposes itself as an MCP server so other agents can query it.

To set that up: \`janus init\`.

## What's in this demo

\`\`\`
${"."}
├── README.md                            ← this file
├── Wrapped/
│   ├── Wrapped-2025.md                  ← yearly Wrapped, deterministic mode
│   └── Wrapped-2025.html                ← same data, HTML rendering
├── Projects/
│   ├── kepler/pulse/2025-09-19--kepler.md
│   └── helios/pulse/2025-09-19--helios.md
└── Timeline/
    └── Daily/2025-09-19.md
\`\`\`

Open \`Wrapped/Wrapped-2025.html\` in a browser to see the flagship artifact. A
real run produces longer prose (LLM-generated rather than deterministic), but
the structure is identical.
`;

export default defineCommand({
  meta: {
    name: "demo",
    description: "Materialize a synthetic vault with sample pulses + the deterministic Wrapped — no Obsidian, no Claude Max required.",
  },
  args: {
    "open": {
      type: "boolean",
      description: "Open the Wrapped HTML in the default browser after generating.",
      default: true,
    },
    "out": {
      type: "string",
      description: "Output directory. Default: a fresh tmpdir.",
    },
  },
  async run({ args }) {
    const outOverride = args.out as string | undefined;
    const out = outOverride
      ? outOverride
      : await mkdtemp(join(tmpdir(), "janus-demo-"));

    await mkdir(join(out, "Wrapped"), { recursive: true });
    await mkdir(join(out, "Projects", "kepler", "pulse"), { recursive: true });
    await mkdir(join(out, "Projects", "helios", "pulse"), { recursive: true });
    await mkdir(join(out, "Timeline", "Daily"), { recursive: true });

    await Promise.all([
      writeFile(join(out, "README.md"), README_DEMO),
      writeFile(join(out, "Wrapped", "Wrapped-2025.md"), wrappedSampleMd),
      writeFile(join(out, "Wrapped", "Wrapped-2025.html"), wrappedSampleHtml),
      writeFile(join(out, "Projects", "kepler", "pulse", "2025-09-19--kepler.md"), PULSE_KEPLER),
      writeFile(join(out, "Projects", "helios", "pulse", "2025-09-19--helios.md"), PULSE_HELIOS),
      writeFile(join(out, "Timeline", "Daily", "2025-09-19.md"), DAILY_ROLLUP),
    ]);

    const wrappedHtml = join(out, "Wrapped", "Wrapped-2025.html");

    console.log("");
    console.log(`Synthetic Janus vault written to:`);
    console.log(`  ${out}`);
    console.log("");
    console.log("Generated artifacts:");
    console.log("  Wrapped/Wrapped-2025.html       ← flagship, open in browser");
    console.log("  Wrapped/Wrapped-2025.md         ← Markdown version");
    console.log("  Projects/kepler/pulse/2025-09-19--kepler.md");
    console.log("  Projects/helios/pulse/2025-09-19--helios.md");
    console.log("  Timeline/Daily/2025-09-19.md");
    console.log("");

    if (args.open as boolean) {
      const opener = process.platform === "darwin"
        ? "open"
        : process.platform === "linux"
          ? "xdg-open"
          : null;
      if (opener) {
        try {
          spawn(opener, [wrappedHtml], { detached: true, stdio: "ignore" }).unref();
          console.log(`Opening Wrapped in your default browser...`);
        } catch {
          console.log(`Could not auto-open. Open this file manually:`);
          console.log(`  ${wrappedHtml}`);
        }
      } else {
        console.log(`Auto-open not supported on ${process.platform}. Open this file manually:`);
        console.log(`  ${wrappedHtml}`);
      }
    }

    console.log("");
    console.log("This is a synthetic demo — none of it is real activity.");
    console.log("To run Janus against your actual projects:");
    console.log("  janus init");
    console.log("");
  },
});
