import { Database } from "bun:sqlite";
import { mkdirSync } from "node:fs";
import { join } from "node:path";

export type PulseStatus = "pending" | "in_progress" | "done" | "failed";

export interface PulseRecord {
  project: string;
  date: string;
  status: PulseStatus;
  attempts: number;
  sessionId: string | null;
  outputPath: string | null;
  promptVersion: string | null;
  error: string | null;
  startedAt: string | null;
  completedAt: string | null;
}

export interface PulseIndexRow {
  project: string;
  date: string;
  section: string;
  body: string;
}

const SCHEMA = `
CREATE TABLE IF NOT EXISTS pulse_state (
  project          TEXT NOT NULL,
  date             TEXT NOT NULL,
  status           TEXT NOT NULL,
  attempts         INTEGER NOT NULL DEFAULT 0,
  session_id       TEXT,
  output_path      TEXT,
  prompt_version   TEXT,
  error            TEXT,
  started_at       TEXT,
  completed_at     TEXT,
  PRIMARY KEY (project, date)
);

CREATE TABLE IF NOT EXISTS pulse_index (
  project   TEXT NOT NULL,
  date      TEXT NOT NULL,
  section   TEXT NOT NULL,
  body      TEXT NOT NULL,
  PRIMARY KEY (project, date, section)
);

-- Baseline of the content generated by the LLM. If the user edits the pulse
-- manually, comparing the on-disk file against this baseline yields the
-- exact diff the feedback loop injects into the next prompt.
CREATE TABLE IF NOT EXISTS pulse_baseline (
  project           TEXT NOT NULL,
  date              TEXT NOT NULL,
  generated_content TEXT NOT NULL,
  generated_at      TEXT NOT NULL,
  PRIMARY KEY (project, date)
);

-- Phase 1C — bookkeeping metadata.
-- Per-project birth dates (first git commit + first pulse in the vault).
-- Enables anniversary detection (Phase 2) and Wrapped birthdays (Phase 3).
CREATE TABLE IF NOT EXISTS project_metadata (
  project          TEXT PRIMARY KEY,
  birth_date_git   TEXT,        -- YYYY-MM-DD of the first commit, null if none
  birth_date_pulse TEXT,        -- YYYY-MM-DD of the first pulse in the vault, null if none
  computed_at      TEXT NOT NULL
);

-- Track lineage: when a track first appeared and when it was last mentioned.
-- Enables open-loop detection (Phase 2) and Top tracks of the year (Phase 3).
CREATE TABLE IF NOT EXISTS track_lineage (
  slug             TEXT NOT NULL,
  project          TEXT NOT NULL,
  first_seen       TEXT NOT NULL,    -- YYYY-MM-DD
  last_mentioned   TEXT NOT NULL,    -- YYYY-MM-DD
  mentions_count   INTEGER NOT NULL DEFAULT 1,
  status           TEXT NOT NULL DEFAULT 'open',  -- open | archived | completed
  PRIMARY KEY (slug, project)
);

-- Decision graph: which pulses reference which ADRs. Enables orphan-decision
-- detection (Phase 2) and biggest-decision for Wrapped (Phase 3).
CREATE TABLE IF NOT EXISTS decision_graph (
  adr_id           TEXT NOT NULL,    -- "ADR-007" or "candidate:<pulse-date>:<decision-N>"
  pulse_date       TEXT NOT NULL,
  project          TEXT NOT NULL,
  reference_type   TEXT NOT NULL,    -- 'mention' | 'candidate' | 'modifies' | 'revertes'
  recorded_at      TEXT NOT NULL,
  PRIMARY KEY (adr_id, pulse_date, project, reference_type)
);

-- Phase 2 U3 — blocker_history: blocker hash + weekly counts. Enables
-- stuck-pattern escalation (same blocker in N+ consecutive weeklies).
CREATE TABLE IF NOT EXISTS blocker_history (
  blocker_hash   TEXT NOT NULL,
  project        TEXT NOT NULL,
  first_seen     TEXT NOT NULL,  -- weekly endDate of the first record
  last_seen      TEXT NOT NULL,  -- weekly endDate of the most recent record
  weekly_count   INTEGER NOT NULL DEFAULT 1,
  sample_text    TEXT NOT NULL,  -- representative blocker text (latest)
  PRIMARY KEY (blocker_hash, project)
);

CREATE INDEX IF NOT EXISTS idx_index_date ON pulse_index(date);
CREATE INDEX IF NOT EXISTS idx_index_section ON pulse_index(project, section);
CREATE INDEX IF NOT EXISTS idx_baseline_project ON pulse_baseline(project, date);
CREATE INDEX IF NOT EXISTS idx_track_lineage_last ON track_lineage(last_mentioned);
CREATE INDEX IF NOT EXISTS idx_track_lineage_project ON track_lineage(project);
CREATE INDEX IF NOT EXISTS idx_decision_graph_adr ON decision_graph(adr_id);
CREATE INDEX IF NOT EXISTS idx_decision_graph_project ON decision_graph(project);
`;

export class Checkpoint {
  private constructor(private readonly db: Database) {}

  static open(stateDir: string): Checkpoint {
    mkdirSync(stateDir, { recursive: true });
    const dbPath = join(stateDir, "state.db");
    const db = new Database(dbPath);
    db.exec("PRAGMA journal_mode = WAL;");
    db.exec(SCHEMA);
    return new Checkpoint(db);
  }

  static openInMemory(): Checkpoint {
    const db = new Database(":memory:");
    db.exec(SCHEMA);
    return new Checkpoint(db);
  }

  get(project: string, date: string): PulseRecord | null {
    const row = this.db
      .query(
        `SELECT project, date, status, attempts, session_id, output_path,
                prompt_version, error, started_at, completed_at
           FROM pulse_state
          WHERE project = ?1 AND date = ?2`,
      )
      .get(project, date) as RawRow | null;
    return row ? mapRow(row) : null;
  }

  isDone(project: string, date: string): boolean {
    return this.get(project, date)?.status === "done";
  }

  markStarted(opts: { project: string; date: string; sessionId: string; promptVersion: string }): void {
    const now = new Date().toISOString();
    this.db
      .query(
        `INSERT INTO pulse_state
           (project, date, status, attempts, session_id, prompt_version, started_at)
         VALUES (?1, ?2, 'in_progress', 1, ?3, ?4, ?5)
         ON CONFLICT(project, date) DO UPDATE SET
           status = 'in_progress',
           attempts = pulse_state.attempts + 1,
           session_id = excluded.session_id,
           prompt_version = excluded.prompt_version,
           started_at = excluded.started_at,
           error = NULL`,
      )
      .run(opts.project, opts.date, opts.sessionId, opts.promptVersion, now);
  }

  markDone(opts: { project: string; date: string; outputPath: string }): void {
    const now = new Date().toISOString();
    this.db
      .query(
        `UPDATE pulse_state
            SET status = 'done',
                output_path = ?3,
                completed_at = ?4,
                error = NULL
          WHERE project = ?1 AND date = ?2`,
      )
      .run(opts.project, opts.date, opts.outputPath, now);
  }

  markFailed(opts: { project: string; date: string; error: string }): void {
    const now = new Date().toISOString();
    this.db
      .query(
        `INSERT INTO pulse_state (project, date, status, attempts, error, started_at, completed_at)
         VALUES (?1, ?2, 'failed', 1, ?3, ?4, ?4)
         ON CONFLICT(project, date) DO UPDATE SET
           status = 'failed',
           error = excluded.error,
           completed_at = ?4`,
      )
      .run(opts.project, opts.date, opts.error, now);
  }

  indexSection(row: PulseIndexRow): void {
    this.db
      .query(
        `INSERT INTO pulse_index (project, date, section, body)
         VALUES (?1, ?2, ?3, ?4)
         ON CONFLICT(project, date, section) DO UPDATE SET body = excluded.body`,
      )
      .run(row.project, row.date, row.section, row.body);
  }

  queryRecent(days: number): PulseRecord[] {
    const cutoff = new Date(Date.now() - days * 86_400_000).toISOString().slice(0, 10);
    const rows = this.db
      .query(
        `SELECT project, date, status, attempts, session_id, output_path,
                prompt_version, error, started_at, completed_at
           FROM pulse_state
          WHERE date >= ?1
          ORDER BY date DESC, project ASC`,
      )
      .all(cutoff) as RawRow[];
    return rows.map(mapRow);
  }

  queryFailed(): PulseRecord[] {
    const rows = this.db
      .query(
        `SELECT project, date, status, attempts, session_id, output_path,
                prompt_version, error, started_at, completed_at
           FROM pulse_state
          WHERE status = 'failed'
          ORDER BY date DESC, project ASC`,
      )
      .all() as RawRow[];
    return rows.map(mapRow);
  }

  saveBaseline(opts: { project: string; date: string; generatedContent: string }): void {
    const now = new Date().toISOString();
    this.db
      .query(
        `INSERT INTO pulse_baseline (project, date, generated_content, generated_at)
         VALUES (?1, ?2, ?3, ?4)
         ON CONFLICT(project, date) DO UPDATE SET
           generated_content = excluded.generated_content,
           generated_at = excluded.generated_at`,
      )
      .run(opts.project, opts.date, opts.generatedContent, now);
  }

  getBaseline(project: string, date: string): { content: string; generatedAt: string } | null {
    const row = this.db
      .query(`SELECT generated_content, generated_at FROM pulse_baseline WHERE project = ?1 AND date = ?2`)
      .get(project, date) as { generated_content: unknown; generated_at: string } | null;
    if (!row) return null;
    return { content: toStringContent(row.generated_content), generatedAt: row.generated_at };
  }

  /** Lists the last N baselines for a project, descending by date. */
  listBaselines(project: string, limit: number): Array<{ date: string; content: string }> {
    const rows = this.db
      .query(
        `SELECT date, generated_content FROM pulse_baseline
          WHERE project = ?1
          ORDER BY date DESC
          LIMIT ?2`,
      )
      .all(project, limit) as Array<{ date: string; generated_content: unknown }>;
    return rows.map((r) => ({ date: r.date, content: toStringContent(r.generated_content) }));
  }

  // ─── Phase 1C: project_metadata ────────────────────────────────────────

  /**
   * Persists a project's birth dates. Call with null when it can't be
   * computed (no git history or no pulses yet).
   */
  upsertProjectMetadata(opts: {
    project: string;
    birthDateGit: string | null;
    birthDatePulse: string | null;
  }): void {
    const now = new Date().toISOString();
    this.db
      .query(
        `INSERT INTO project_metadata (project, birth_date_git, birth_date_pulse, computed_at)
         VALUES (?1, ?2, ?3, ?4)
         ON CONFLICT(project) DO UPDATE SET
           birth_date_git = excluded.birth_date_git,
           birth_date_pulse = excluded.birth_date_pulse,
           computed_at = excluded.computed_at`,
      )
      .run(opts.project, opts.birthDateGit, opts.birthDatePulse, now);
  }

  getProjectMetadata(project: string): {
    project: string;
    birthDateGit: string | null;
    birthDatePulse: string | null;
    computedAt: string;
  } | null {
    const row = this.db
      .query(`SELECT project, birth_date_git, birth_date_pulse, computed_at FROM project_metadata WHERE project = ?1`)
      .get(project) as { project: string; birth_date_git: string | null; birth_date_pulse: string | null; computed_at: string } | null;
    if (!row) return null;
    return {
      project: row.project,
      birthDateGit: row.birth_date_git,
      birthDatePulse: row.birth_date_pulse,
      computedAt: row.computed_at,
    };
  }

  // ─── Phase 1C: track_lineage ────────────────────────────────────────────

  /**
   * Records a track mention on a date (typically the date of the
   * weekly/monthly that materialized it). Idempotent upsert: if the track
   * already exists for that project, updates `last_mentioned` and adds 1 to
   * `mentions_count` ONLY if the date is greater than or equal to
   * `last_mentioned` (does not increment for dates before what's already
   * recorded — avoids double counting on regeneration).
   */
  recordTrackMention(opts: { slug: string; project: string; date: string; status?: string }): void {
    const status = opts.status ?? "open";
    const existing = this.db
      .query(`SELECT first_seen, last_mentioned, mentions_count, status FROM track_lineage WHERE slug = ?1 AND project = ?2`)
      .get(opts.slug, opts.project) as { first_seen: string; last_mentioned: string; mentions_count: number; status: string } | null;
    if (!existing) {
      this.db
        .query(
          `INSERT INTO track_lineage (slug, project, first_seen, last_mentioned, mentions_count, status)
           VALUES (?1, ?2, ?3, ?3, 1, ?4)`,
        )
        .run(opts.slug, opts.project, opts.date, status);
      return;
    }
    const firstSeen = opts.date < existing.first_seen ? opts.date : existing.first_seen;
    const lastMentioned = opts.date > existing.last_mentioned ? opts.date : existing.last_mentioned;
    const newCount = opts.date > existing.last_mentioned ? existing.mentions_count + 1 : existing.mentions_count;
    this.db
      .query(
        `UPDATE track_lineage SET first_seen = ?3, last_mentioned = ?4, mentions_count = ?5, status = ?6
          WHERE slug = ?1 AND project = ?2`,
      )
      .run(opts.slug, opts.project, firstSeen, lastMentioned, newCount, status);
  }

  listTrackLineage(opts?: { project?: string }): Array<{
    slug: string;
    project: string;
    firstSeen: string;
    lastMentioned: string;
    mentionsCount: number;
    status: string;
  }> {
    const rows = opts?.project
      ? (this.db
          .query(`SELECT slug, project, first_seen, last_mentioned, mentions_count, status FROM track_lineage WHERE project = ?1 ORDER BY last_mentioned DESC`)
          .all(opts.project) as Array<{ slug: string; project: string; first_seen: string; last_mentioned: string; mentions_count: number; status: string }>)
      : (this.db
          .query(`SELECT slug, project, first_seen, last_mentioned, mentions_count, status FROM track_lineage ORDER BY last_mentioned DESC`)
          .all() as Array<{ slug: string; project: string; first_seen: string; last_mentioned: string; mentions_count: number; status: string }>);
    return rows.map((r) => ({
      slug: r.slug,
      project: r.project,
      firstSeen: r.first_seen,
      lastMentioned: r.last_mentioned,
      mentionsCount: r.mentions_count,
      status: r.status,
    }));
  }

  setTrackStatus(opts: { slug: string; project: string; status: string }): void {
    this.db
      .query(`UPDATE track_lineage SET status = ?3 WHERE slug = ?1 AND project = ?2`)
      .run(opts.slug, opts.project, opts.status);
  }

  // ─── Phase 1C: decision_graph ───────────────────────────────────────────

  /**
   * Records a reference from a pulse to an ADR. Idempotent on the composite
   * PK (adr_id, pulse_date, project, reference_type).
   */
  recordDecisionReference(opts: {
    adrId: string;
    pulseDate: string;
    project: string;
    referenceType: "mention" | "candidate" | "modifies" | "revertes";
  }): void {
    const now = new Date().toISOString();
    this.db
      .query(
        `INSERT INTO decision_graph (adr_id, pulse_date, project, reference_type, recorded_at)
         VALUES (?1, ?2, ?3, ?4, ?5)
         ON CONFLICT(adr_id, pulse_date, project, reference_type) DO NOTHING`,
      )
      .run(opts.adrId, opts.pulseDate, opts.project, opts.referenceType, now);
  }

  listDecisionReferences(opts?: { adrId?: string; project?: string }): Array<{
    adrId: string;
    pulseDate: string;
    project: string;
    referenceType: string;
    recordedAt: string;
  }> {
    type Row = { adr_id: string; pulse_date: string; project: string; reference_type: string; recorded_at: string };
    let rows: Row[];
    if (opts?.adrId) {
      rows = this.db
        .query(`SELECT adr_id, pulse_date, project, reference_type, recorded_at FROM decision_graph WHERE adr_id = ?1 ORDER BY pulse_date DESC`)
        .all(opts.adrId) as Row[];
    } else if (opts?.project) {
      rows = this.db
        .query(`SELECT adr_id, pulse_date, project, reference_type, recorded_at FROM decision_graph WHERE project = ?1 ORDER BY pulse_date DESC`)
        .all(opts.project) as Row[];
    } else {
      rows = this.db
        .query(`SELECT adr_id, pulse_date, project, reference_type, recorded_at FROM decision_graph ORDER BY pulse_date DESC`)
        .all() as Row[];
    }
    return rows.map((r) => ({
      adrId: r.adr_id,
      pulseDate: r.pulse_date,
      project: r.project,
      referenceType: r.reference_type,
      recordedAt: r.recorded_at,
    }));
  }

  // ─── Phase 2 U3: blocker_history ────────────────────────────────────────

  /**
   * Records a blocker appearance in a weekly. If the hash already exists,
   * increments weekly_count by 1 ONLY if weeklyEndDate > last_seen (avoids
   * double counting on regeneration of the same weekly).
   */
  recordBlockerOccurrence(opts: {
    blockerHash: string;
    project: string;
    weeklyEndDate: string;
    sampleText: string;
  }): void {
    const existing = this.db
      .query(`SELECT first_seen, last_seen, weekly_count FROM blocker_history WHERE blocker_hash = ?1 AND project = ?2`)
      .get(opts.blockerHash, opts.project) as { first_seen: string; last_seen: string; weekly_count: number } | null;
    if (!existing) {
      this.db
        .query(
          `INSERT INTO blocker_history (blocker_hash, project, first_seen, last_seen, weekly_count, sample_text)
           VALUES (?1, ?2, ?3, ?3, 1, ?4)`,
        )
        .run(opts.blockerHash, opts.project, opts.weeklyEndDate, opts.sampleText);
      return;
    }
    if (opts.weeklyEndDate <= existing.last_seen) return; // avoid double counting
    this.db
      .query(
        `UPDATE blocker_history
            SET last_seen = ?3, weekly_count = weekly_count + 1, sample_text = ?4
          WHERE blocker_hash = ?1 AND project = ?2`,
      )
      .run(opts.blockerHash, opts.project, opts.weeklyEndDate, opts.sampleText);
  }

  listBlockerHistory(opts?: { minCount?: number; project?: string }): Array<{
    blockerHash: string;
    project: string;
    firstSeen: string;
    lastSeen: string;
    weeklyCount: number;
    sampleText: string;
  }> {
    type Row = {
      blocker_hash: string;
      project: string;
      first_seen: string;
      last_seen: string;
      weekly_count: number;
      sample_text: string;
    };
    const minCount = opts?.minCount ?? 1;
    let rows: Row[];
    if (opts?.project) {
      rows = this.db
        .query(
          `SELECT blocker_hash, project, first_seen, last_seen, weekly_count, sample_text
             FROM blocker_history WHERE project = ?1 AND weekly_count >= ?2
             ORDER BY weekly_count DESC, last_seen DESC`,
        )
        .all(opts.project, minCount) as Row[];
    } else {
      rows = this.db
        .query(
          `SELECT blocker_hash, project, first_seen, last_seen, weekly_count, sample_text
             FROM blocker_history WHERE weekly_count >= ?1
             ORDER BY weekly_count DESC, last_seen DESC`,
        )
        .all(minCount) as Row[];
    }
    return rows.map((r) => ({
      blockerHash: r.blocker_hash,
      project: r.project,
      firstSeen: r.first_seen,
      lastSeen: r.last_seen,
      weeklyCount: r.weekly_count,
      sampleText: r.sample_text,
    }));
  }

  /** Quick counter — how many pulses reference each ADR. Useful for "biggest decision". */
  countReferencesByAdr(): Array<{ adrId: string; count: number }> {
    const rows = this.db
      .query(`SELECT adr_id, COUNT(*) AS c FROM decision_graph GROUP BY adr_id ORDER BY c DESC`)
      .all() as Array<{ adr_id: string; c: number }>;
    return rows.map((r) => ({ adrId: r.adr_id, count: r.c }));
  }

  close(): void {
    this.db.close();
  }
}

interface RawRow {
  project: string;
  date: string;
  status: PulseStatus;
  attempts: number;
  session_id: string | null;
  output_path: string | null;
  prompt_version: string | null;
  error: string | null;
  started_at: string | null;
  completed_at: string | null;
}

function toStringContent(raw: unknown): string {
  if (typeof raw === "string") return raw;
  if (raw instanceof Uint8Array) return new TextDecoder().decode(raw);
  if (raw == null) return "";
  return String(raw);
}

function mapRow(r: RawRow): PulseRecord {
  return {
    project: r.project,
    date: r.date,
    status: r.status,
    attempts: r.attempts,
    sessionId: r.session_id,
    outputPath: r.output_path,
    promptVersion: r.prompt_version,
    error: r.error,
    startedAt: r.started_at,
    completedAt: r.completed_at,
  };
}

