import { existsSync } from "node:fs";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { JanusConfig, ProjectConfig } from "../config/types.ts";
import { syncRoadmaps } from "./sync-roadmaps.ts";

interface PulseFrontmatter {
  date: string;
  project: string;
  status: string;
  commits: number;
  files_changed: number;
  sessions_analyzed: number;
  insertions: number;
  deletions: number;
  risks: number;
  prompt_version: string;
  /** Marker for drafts auto-generated by Janus (in _roadmap.md / STRATEGY.md). */
  needs_review: string | boolean;
}

interface ParsedPulse {
  filename: string;        // without .md
  path: string;
  date: string;
  frontmatter: Partial<PulseFrontmatter>;
  /** Full body content (without frontmatter). */
  body: string;
}

const PLACEHOLDER_ROADMAP_MARKER = "Edit this file with the milestones";
const LEGACY_ROADMAP_MARKER = "Editá este archivo con los hitos";

export interface EnrichOptions {
  /** Only process this project (by name). */
  onlyProject?: string;
}

export interface EnrichResult {
  projectsProcessed: number;
  indexesWritten: number;
  roadmapsWritten: number;
  strategiesWritten: number;
}

export async function enrichVault(config: JanusConfig, opts: EnrichOptions = {}): Promise<EnrichResult> {
  const result: EnrichResult = {
    projectsProcessed: 0,
    indexesWritten: 0,
    roadmapsWritten: 0,
    strategiesWritten: 0,
  };

  for (const project of config.projects) {
    if (opts.onlyProject && project.name !== opts.onlyProject) continue;
    const vaultRelPath = relativeVaultPath(config.obsidianVault, project.obsidianPath);
    const pulses = await loadProjectPulses(project);

    if (await enrichIndex(project, vaultRelPath, pulses)) result.indexesWritten += 1;
    if (await maybeRegenerateRoadmap(project, pulses)) result.roadmapsWritten += 1;
    if (await maybeCreateStrategy(project)) result.strategiesWritten += 1;
    result.projectsProcessed += 1;
  }

  return result;
}

async function loadProjectPulses(project: ProjectConfig): Promise<ParsedPulse[]> {
  const dir = join(project.obsidianPath, "pulse");
  if (!existsSync(dir)) return [];
  const entries = await readdir(dir);
  const pulses: ParsedPulse[] = [];
  for (const name of entries) {
    if (!name.endsWith(".md")) continue;
    const m = name.match(/^(\d{4}-\d{2}-\d{2})-(.+)\.md$/);
    if (!m) continue;
    const full = join(dir, name);
    const content = await readFile(full, "utf-8");
    const { frontmatter, body } = splitFrontmatter(content);
    pulses.push({
      filename: name.replace(/\.md$/, ""),
      path: full,
      date: m[1]!,
      frontmatter: parseFrontmatter(frontmatter),
      body,
    });
  }
  // descending order by date
  pulses.sort((a, b) => (a.date < b.date ? 1 : -1));
  return pulses;
}

function splitFrontmatter(content: string): { frontmatter: string; body: string } {
  const m = content.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!m) return { frontmatter: "", body: content };
  return { frontmatter: m[1] ?? "", body: m[2] ?? "" };
}

function parseFrontmatter(raw: string): Partial<PulseFrontmatter> {
  const out: Record<string, unknown> = {};
  for (const line of raw.split("\n")) {
    const m = line.match(/^([a-z_]+):\s*(.+)$/i);
    if (!m) continue;
    const key = m[1]!;
    let value: unknown = (m[2] ?? "").trim();
    if (typeof value === "string" && /^-?\d+$/.test(value)) value = parseInt(value, 10);
    out[key] = value;
  }
  return out as Partial<PulseFrontmatter>;
}

function relativeVaultPath(vaultRoot: string, projectObsidianPath: string): string {
  return projectObsidianPath.startsWith(vaultRoot)
    ? projectObsidianPath.slice(vaultRoot.length).replace(/^\/+/, "")
    : projectObsidianPath;
}

function predominantStatus(pulses: ParsedPulse[]): string {
  if (pulses.length === 0) return "idle";
  const counts: Record<string, number> = {};
  for (const p of pulses) {
    const s = String(p.frontmatter.status ?? "idle");
    counts[s] = (counts[s] ?? 0) + 1;
  }
  return Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] ?? "idle";
}

function extractDecisions(body: string): string[] {
  // > [!quote] Decisions
  // > - [sesión `xyz`] ... ^decision-1
  const lines = body.split("\n");
  const out: string[] = [];
  let inDecisions = false;
  for (const line of lines) {
    if (/^>\s*\[!quote\]\s*Decisions/i.test(line)) {
      inDecisions = true;
      continue;
    }
    if (inDecisions) {
      if (!line.startsWith(">")) {
        inDecisions = false;
        continue;
      }
      const m = line.match(/^>\s*-\s*(.+)$/);
      if (m && m[1]) out.push(m[1].trim());
    }
  }
  return out;
}

function extractRoadmapDraft(body: string): { objective: string; milestones: string[]; backlog: string[] } | null {
  // Find the "Inferred roadmap" callout (legacy: "Roadmap inferido")
  let startIdx = body.indexOf("Inferred roadmap");
  if (startIdx === -1) startIdx = body.indexOf("Roadmap inferido");
  if (startIdx === -1) return null;
  // Keep everything that follows in the callout (lines starting with `>`)
  const lines = body.slice(startIdx).split("\n");
  const calloutLines: string[] = [];
  for (const line of lines) {
    if (line.startsWith(">")) {
      calloutLines.push(line.replace(/^>\s?/, ""));
    } else if (calloutLines.length > 0 && line.trim() === "") {
      // Blank lines inside the callout usually come as "> " — if a fully
      // blank line arrives, we've probably exited the callout.
      break;
    }
  }
  const inner = calloutLines.join("\n");

  const objective = extractSection(inner, "Inferred objective") || extractSection(inner, "Objetivo inferido");
  const milestonesRaw = extractSection(inner, "Inferred milestones") || extractSection(inner, "Hitos inferidos");
  const backlogRaw = extractSection(inner, "Inferred backlog") || extractSection(inner, "Backlog inferido");

  const milestones = extractBullets(milestonesRaw).map(stripCheckbox);
  const backlog = extractBullets(backlogRaw).map(stripCheckbox);

  if (!objective && milestones.length === 0 && backlog.length === 0) return null;
  return { objective: objective.trim(), milestones, backlog };
}

function extractSection(text: string, header: string): string {
  const lines = text.split("\n");
  const out: string[] = [];
  let inSection = false;
  for (const line of lines) {
    if (line.match(new RegExp(`^#{1,4}\\s+.*${escapeRegex(header)}`, "i"))) {
      inSection = true;
      continue;
    }
    if (inSection) {
      if (line.match(/^#{1,4}\s+/)) {
        inSection = false;
        continue;
      }
      out.push(line);
    }
  }
  return out.join("\n").trim();
}

function extractBullets(text: string): string[] {
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.startsWith("-"))
    .map((l) => l.replace(/^-\s*/, ""));
}

function stripCheckbox(s: string): string {
  return s.replace(/^\[[ xX]\]\s*/, "");
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function aliasFor(project: string): string {
  const parts = project.split("-");
  return parts.length <= 1 ? project : parts.slice(1).join("-");
}

function nowISODate(): string {
  return new Date().toISOString().slice(0, 10);
}

async function enrichIndex(project: ProjectConfig, vaultRelPath: string, pulses: ParsedPulse[]): Promise<boolean> {
  const lastPulse = pulses[0];
  const last7Pulses = pulses.filter((p) => {
    const d = new Date(`${p.date}T00:00:00`);
    const seven = new Date();
    seven.setDate(seven.getDate() - 7);
    return d >= seven;
  });

  const totalCommits = last7Pulses.reduce((acc, p) => acc + (Number(p.frontmatter.commits) || 0), 0);
  const totalSessions = last7Pulses.reduce((acc, p) => acc + (Number(p.frontmatter.sessions_analyzed) || 0), 0);
  const totalRisks = last7Pulses.reduce((acc, p) => acc + (Number(p.frontmatter.risks) || 0), 0);
  const activeDays = last7Pulses.filter((p) => String(p.frontmatter.status) !== "idle").length;
  const status = predominantStatus(last7Pulses);

  // Decisiones recientes (max 10)
  const recentDecisions: string[] = [];
  for (const p of last7Pulses) {
    const decisions = extractDecisions(p.body);
    for (const d of decisions) {
      if (recentDecisions.length >= 10) break;
      recentDecisions.push(`- [[${p.filename}|${p.date}]]: ${d}`);
    }
    if (recentDecisions.length >= 10) break;
  }

  const tldrEmbed = lastPulse
    ? `![[${lastPulse.filename}#TL;DR]]\n\n→ [[${lastPulse.filename}|View full pulse]]`
    : "(no pulses yet)";

  const target = join(project.obsidianPath, "_index.md");

  // Respect a frozen dashboard: enrichIndex normally rewrites _index.md on every
  // run, so any manual note a user adds would be lost. Setting
  // `managed_by_janus: false` in the frontmatter opts out and freezes the file.
  if (existsSync(target)) {
    const existingFm = parseFrontmatter(splitFrontmatter(await readFile(target, "utf-8")).frontmatter) as Record<string, unknown>;
    if (String(existingFm.managed_by_janus ?? "") === "false") return false;
  }

  const content = `---
type: project-index
project: ${project.name}
tags: [project-index]
aliases: ["${aliasFor(project.name)}-index"]
managed_by_janus: true
---

# ${project.name}

> [!summary]+ Current state
> Embed of the latest pulse's TL;DR + summary metrics for the last 7 days.
> To stop Janus from overwriting this dashboard, set \`managed_by_janus: false\` in the frontmatter.

## TL;DR of latest pulse

${tldrEmbed}

## Last 7 days

| Metric | Value |
|---|---|
| Active days | ${activeDays} / ${Math.min(last7Pulses.length, 7)} |
| Total commits | ${totalCommits} |
| Total sessions | ${totalSessions} |
| Open risks (sum) | ${totalRisks} |
| Predominant status | \`${status}\` |

## Roadmap

![[_roadmap]]

## Strategy

See [[STRATEGY]] — if it says \`needs_review: true\`, it's still a template.

## Recent decisions (last 7 days)

${recentDecisions.length > 0 ? recentDecisions.join("\n") : "(no decisions detected in recent pulses)"}

## Open risks

\`\`\`dataview
TABLE WITHOUT ID file.link AS Pulse, date, risks
FROM "${vaultRelPath}/pulse"
WHERE contains(tags, "pulse") AND risks > 0
SORT date DESC
LIMIT 5
\`\`\`

## Recent pulses

\`\`\`dataview
TABLE WITHOUT ID file.link AS Pulse, date, status, commits, risks
FROM "${vaultRelPath}/pulse"
WHERE contains(tags, "pulse")
SORT date DESC
LIMIT 14
\`\`\`

## Links

- Hub: [[${project.name}]]
- [[_roadmap|Roadmap]] · [[STRATEGY|Strategy]]
- MOCs: [[Projects MOC]] · [[Decisions MOC]] · [[Risks MOC]] · [[Weekly MOC]]
- Dashboards: [[Janus Pulse|Global view]] · [[Open Risks]] · [[Drift]] · [[Inferring]]
`;

  await writeFile(target, content);
  return true;
}

async function maybeRegenerateRoadmap(project: ProjectConfig, pulses: ParsedPulse[]): Promise<boolean> {
  const target = join(project.obsidianPath, "_roadmap.md");

  if (existsSync(target)) {
    const existing = await readFile(target, "utf-8");
    const fm = parseFrontmatter(splitFrontmatter(existing).frontmatter);
    const needsReview = String(fm.needs_review ?? "") === "true";
    const isPlaceholder = existing.includes(PLACEHOLDER_ROADMAP_MARKER) || existing.includes(LEGACY_ROADMAP_MARKER);
    if (!needsReview && !isPlaceholder) {
      return false; // user edited → don't touch
    }
  }

  // Find the most recent pulse with an inferred roadmap.
  const candidate = pulses.find((p) =>
    String(p.frontmatter.status) === "inferring"
    && (p.body.includes("Inferred roadmap") || p.body.includes("Roadmap inferido"))
  );
  if (!candidate) {
    // No inferring pulse to derive a roadmap from. Fall back to syncRoadmaps,
    // which mirrors a repo ROADMAP.md, syncs from a "Vs Roadmap" pulse callout,
    // or — failing both — writes a PENDIENTE placeholder. This guarantees the
    // `![[_roadmap]]` embed in _index.md is never broken, closing the old
    // "creating placeholders isn't our concern today" gap. syncRoadmaps re-checks
    // user-edited (needs_review:false) itself, so this is safe to call here.
    const sync = await syncRoadmaps({
      projects: [{ name: project.name, obsidianPath: project.obsidianPath, repoPath: project.repoPath }],
    });
    return sync.roadmapsSyncedFromRepo + sync.roadmapsSyncedFromPulse + sync.roadmapsPendingNoSource > 0;
  }

  const draft = extractRoadmapDraft(candidate.body);
  if (!draft) return false;

  const objective = draft.objective || "(not extracted from pulses — fill in manually)";
  const milestonesMd = draft.milestones.length > 0
    ? draft.milestones.map((m) => `- [ ] ${m}`).join("\n")
    : "- [ ] (no milestones inferred — fill in)";
  const backlogMd = draft.backlog.length > 0
    ? draft.backlog.map((b) => `- ${b}`).join("\n")
    : "- (no backlog inferred — fill in)";

  const content = `---
type: roadmap
project: ${project.name}
generated_at: ${new Date().toISOString()}
source: pulse-inference
needs_review: true
---

# Roadmap — ${project.name}

> [!warning] DRAFT generated by Janus
> This roadmap was inferred automatically from pulse \`${candidate.filename}\`. Review it, adjust milestones and priorities, and once it's ready remove \`needs_review: true\` from the frontmatter. Future pulses will respect the edited content.

## Objective

${objective}

## Active milestones this week

${milestonesMd}

## Near backlog

${backlogMd}

## Notes

- Generated on ${nowISODate()} from pulse [[${candidate.filename}|${candidate.date}]].
- If you want Janus to re-infer, delete this file or leave \`needs_review: true\`.
`;

  await writeFile(target, content);
  return true;
}

async function maybeCreateStrategy(project: ProjectConfig): Promise<boolean> {
  const target = join(project.obsidianPath, "STRATEGY.md");
  if (existsSync(target)) return false;

  const content = `---
type: strategy
project: ${project.name}
status: draft
needs_review: true
---

# STRATEGY — ${project.name}

> [!info] Template — fill in
> Fill the sections below. Janus uses them in pulses for the "Vs Strategic North Star" section — without this, reports stay in \`inferring\` mode.

## Target problem

(What concrete problem does this project solve? 2-3 lines.)

## Approach

(How do you solve it? The chosen stack/approach and why.)

## Who it's for

(Who's the user? Type, context, urgency.)

## Key metrics

(The 2-3 metrics that matter. e.g.:
- Activation rate
- Time-to-first-pulse
- % of users who return within a week)

## Work tracks

- **Track 1**: <name> — <1-2 line description>
- **Track 2**: ...

## Not working on

(Things explicitly NOT in scope right now.)

## Notes

- Generated on ${nowISODate()} as a template. Delete this block once the sections are filled and leave \`needs_review: false\`.
`;
  await writeFile(target, content);
  return true;
}
